version: "3"
services:
  app:
    container_name: "jphacks"
    build: .
    user: root
    volumes:
      - ./:/workspace
    ports:
      - 8881:8881
    tty: True
    depends_on:       
      - db            
  db:                 
    image: postgres:14
    env_file:
      - .env
    ports: 
        - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
