# Generated by Django 3.2.8 on 2021-10-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('organization_name', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('person_name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=200, verbose_name='日報')),
                ('person_id', models.IntegerField(default=0, unique=True)),
                ('score', models.FloatField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
