# Generated by Django 3.2.8 on 2021-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(default='たいとる', max_length=100),
            preserve_default=False,
        ),
    ]
