# Generated by Django 3.2.8 on 2021-10-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20211029_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='作成日'),
        ),
    ]
