# Generated by Django 3.2.8 on 2021-10-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_dailyreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
