# Generated by Django 3.2.8 on 2021-10-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_dailyreport_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='person_id',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
