# Generated by Django 3.2.8 on 2021-10-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_dailyreport_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='person_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
