# Generated by Django 3.2.8 on 2021-10-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_alter_dailyreport_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='作成日', null=True),
        ),
    ]
